### PR TITLE
fixing dc and xdr stat collection [TOOLS-3056]

### LINKED ISSUE #70: Error parsing cmdConfigRacks for community edition cluster
Hi team, 

I'm trying to set up the [aerospike-backup-service](https://github.com/aerospike/aerospike-backup-service), but the cluster config parsing logic, whenever a backup is triggered, is crashing when it tries to parse the `racks:` config for a community edition cluster.

I suppose the backup service should work with a community edition cluster, is that correct?

Details of the issue:

`
Cluster build: 8.0.0.5
aerospike-backup-service: v3.0.0
aerospike-management-lib: v1.7.0

$ asinfo -v 'racks:'
ERROR:25:enterprise only

Error message: recovered from panic: runtime error: index out of range [1] with length 1

Panic location: https://github.com/aerospike/aerospike-management-lib/blob/c0ab0c2f8c40586b5fb2b04e46206e3211494d17/info/as_parser.go#L1618

Parameters of the function call: 
str: "ERROR:25:enterprise only" del: ":" sep: "="
`

### PR DESCRIPTION
**Pull request by tanmayja**
Changes included in this PR:

1. Fix XDR and DC stat collections.
2. bins/<namespace name> command is removed from 7.0.
3. Removing server version pre5 support.
4. Remove throughput command.
5. Fix generate command panic for community edition.
6. Providing wrapper functions to set configs in aerospike cluster.

### CODE REVIEW

File: asconfig/as_getconfig.go [hunk 1]
```diff
@@ -13,44 +14,54 @@ import (
...
-func GetASConfig(path *string, conn *deployment.ASConn, aerospikePolicy *aero.ClientPolicy) (
-	confToReturn interface{}, err error) {
+func GetASConfig(paths []string, conn *deployment.ASConn, aerospikePolicy *aero.ClientPolicy) (
+	confToReturn map[string]interface{}, err error) {
 	h := aero.Host{
 		Name:    conn.AerospikeHostName,
 		Port:    conn.AerospikePort,
 		TLSName: conn.AerospikeTLSName,
 	}
 	asinfo := info.NewAsInfo(conn.Log, &h, aerospikePolicy)
```
Comment (a-spiker) [inline asconfig/as_getconfig.go:24]: Kindly close the connection opened by the client, there is a connection leak

File: asconfig/as_getconfig.go [hunk 2]
```diff
@@ -13,44 +14,56 @@ import (
...
-	confToReturn, err = traverseConfig(conn.Log, confToReturn, *path, ctxs[0])
-	if err != nil {
-		conn.Log.Error(err, "failed to traverse config")
-		return nil, err
+	for _, path := range paths {
+		ctx := ContextKey(path)
+
+		ctxConf := conf[ctx]
+		if ctxConf == nil {
+			conn.Log.Info("Config is nil", "context", ctxConf)
```
Comment (a-spiker) [inline asconfig/as_getconfig.go:56]:
```
confToReturn[path] = nil
continue
```

should we continue to process other paths or stop here?

File: info/as_parser.go [hunk 3]
```diff
@@ -418,7 +410,19 @@ func ParseNamespaceNames(m map[string]string) []string {
...
-	return getNames(m[constStatDCNames])
+	rawXDRConfig, exists := m[cmdConfigXDR]
+	if !exists || rawXDRConfig == "" {
+		return []string{}
+	}
+
+	xdrConfig := ParseIntoMap(rawXDRConfig, ";", "=")
+
+	rawNames, ok := xdrConfig[constStatDCNames].(string)
+	if !ok || rawNames == "" {
```
Comment (a-spiker) [inline info/as_parser.go:421]: if not ok , which means parsing failure. should we log this ... else error will be silently dropped with empty string

File: asconfig/as_setconfig.go [hunk 4]
```diff
@@ -464,3 +465,104 @@ func rearrangeConfigMap(log logr.Logger, configMap DynamicConfigMap) []string {
...
+			continue
+		}
+
+		if ok, _ := isListField(k); ok {
+			// Ignore these fields as these operations are not update operations
+			//TODO: Should we through an error if these fields are present in the configMap patch?
+			continue
+		}
+
+		valueMap := make(map[OpType]interface{})
```
Comment (a-spiker) [inline asconfig/as_setconfig.go:516]: can we use sync pool outside the loop

valueMapPool := sync.Pool{
    New: func() interface{} {
        return make(map[OpType]interface{})
    },
}

**Review by a-spiker — CHANGES_REQUESTED** [review]
requested minor reviews

File: asconfig/as_getconfig.go (hunk 2 above)
Comment (a-spiker) [reply asconfig/as_getconfig.go:56]: Resolved after discussion , currently we are not returning partial success.

File: info/as_parser.go (hunk 3 above)
Comment (a-spiker) [reply info/as_parser.go:421]: Resolved after discussion, as we are not logging parsing problems under the current scope.

File: asconfig/as_setconfig.go (hunk 4 above)
Comment (a-spiker) [reply asconfig/as_setconfig.go:516]: currently we cannot resuse the maps as they are all forming the config tree.

File: info/as_parser.go [hunk 5]
```diff
@@ -543,7 +549,11 @@ func (info *AsInfo) createConfigCmdList(
 			ConfigServiceContext, ConfigNetworkContext, ConfigNamespaceContext,
 			ConfigSetContext, ConfigXDRContext, ConfigDCContext,
 			ConfigSecurityContext, ConfigLoggingContext, ConfigDCNames,
-			ConfigNamespaceNames, ConfigLogIDs, ConfigRacksContext,
+			ConfigNamespaceNames, ConfigLogIDs,
```
Comment (abhishekdwivedi3060) [inline info/as_parser.go:552]: Seems like ConfigDCContext, ConfigDCNames, ConfigNamespaceNames, ConfigLogIDs are unused.
Please confirm the use and remove them

File: info/as_parser.go [hunk 6]
```diff
@@ -920,7 +890,6 @@ func parseStatInfo(rawMap map[string]string) lib.Stats {
 	statMap := make(lib.Stats)
 
 	statMap["service"] = parseBasicInfo(rawMap[ConstStat])
-	statMap["xdr"] = parseBasicInfo(rawMap[constStatXDR])
```
Comment (abhishekdwivedi3060) [inline info/as_parser.go:923]: Q: Will this removal cause any backward incompatibility? meaning is there a need to populate the `xdr` stats with `cmdConfigXDR` cmd or removing completely is fine?

**Review by abhishekdwivedi3060 — CHANGES_REQUESTED** [review]

**Review by abhishekdwivedi3060 — APPROVED** [review]

**Review by a-spiker — APPROVED** [review]
LGTM
